### ISSUE TITLE
Unit testing/coverage

### ISSUE THREAD

**Issue by scniro** [scniro/react-codemirror2#23]
While writing some basic tests, I've stumbled upon the difficulty of testing components with Enzyme/Jest due to the nature of `codemirror` creating an editor after the component has mounted. Enzyme seems to not see this in it's wrapper, thus any sort of API methods I expect to use are simply not there.
 
Any PR's and/or suggestions are more than welcome. I plan to leave this as a long running open issue until we get to > 90% coverage 😎

**Comment by KevinGrandon** [comment]
Just stopping by and not sure if you've figured out your problems or not. I noticed that you were using `Enzyme.shallow` which does not run the react component lifecycle. I think you'll need to perform a full [mount](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md) in case you need to run lifecycle methods.

**Comment by scniro** [comment]
@KevinGrandon Hey thanks for checking in on this. I've been working on a 4.x release for a bit that'll be coming up soon and I've managed to get around ~85% coverage which is definitely heading in the right direction. I have been using `.mount` where it makes sense, but there is still the struggle of dealing with then-later-rendered DOM escaping the enzyme API. I've found a few creative ways to get around it, but it's still less than ideal. I'll chalk it up as a just-deal-with-it because testing a third-party component that's simply shipped in a react container is not an ideal situation anyways. Thank you for your interest on this!

**Comment by PatrM** [comment]
I just gonna add my Issue here, since I seem to be struggling with something similar.

```Javascript
TypeError: document.body.createTextRange is not a function

      at range (node_modules/codemirror/lib/codemirror.js:94:25)
      at hasBadBidiRects (node_modules/codemirror/lib/codemirror.js:1244:12)
      at buildLineContent (node_modules/codemirror/lib/codemirror.js:1825:9)
      at updateExternalMeasurement (node_modules/codemirror/lib/codemirror.js:2429:28)
      at prepareMeasureForLine (node_modules/codemirror/lib/codemirror.js:2465:14)
      at measureChar (node_modules/codemirror/lib/codemirror.js:2438:34)
      at endOperation_R2 (node_modules/codemirror/lib/codemirror.js:3788:24)
      at endOperations (node_modules/codemirror/lib/codemirror.js:3754:7)
      at node_modules/codemirror/lib/codemirror.js:3741:5
      at finishOperation (node_modules/codemirror/lib/codemirror.js:2119:5)
      at endOperation (node_modules/codemirror/lib/codemirror.js:3738:3)
      at new CodeMirror$1 (node_modules/codemirror/lib/codemirror.js:7824:3)
      at CodeMirror$1 (node_modules/codemirror/lib/codemirror.js:7765:49)
      at Controlled.Object.<anonymous>.Controlled.componentDidMount (node_modules/react-codemirror2/index.js:264:23)
```
I'm just running the basic `renders without crashing` test, starting & using the app works just fine.

@scniro did you have any success solving this issue?

I'll let you guys know if i find something in the meantime!

**Comment by scniro** [comment]
@PatrM @KevinGrandon I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.
